// Generates real Groth16 proofs with the production circuit artifacts and writes them
// as a Solidity library, so the Foundry suite exercises the actual verifier end to end.
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
// @ts-expect-error snarkjs ships no types
import * as snarkjs from 'snarkjs'
import { createNote, generateKeys, proveWithdraw, toHex, toMetaAddress, type Hex, type Snarkjs } from '../src'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const circuits = join(repo, 'frontend', 'public', 'circuits')
const artifacts = {
  wasm: join(circuits, 'stealth_withdraw.wasm'),
  zkey: join(circuits, 'stealth_withdraw.zkey'),
}

export const RECIPIENT: Hex = '0x000000000000000000000000000000000000b0b0'
export const RELAYER: Hex = '0x000000000000000000000000000000000000fee0'

const cases = [
  { name: 'RELAYED', relayer: RELAYER, fee: 250_000n }, // 0.25 USDG
  { name: 'SELF', relayer: '0x0000000000000000000000000000000000000000' as Hex, fee: 0n },
]

const vkey = JSON.parse(readFileSync(join(circuits, 'verification_key.json'), 'utf8'))
const keys = generateKeys()
const out: string[] = []
for (const c of cases) {
  const note = createNote(toMetaAddress(keys))
  const { proof, publicSignals, raw } = await proveWithdraw(
    snarkjs as Snarkjs,
    { spendPriv: keys.spendPriv, sharedSecret: note.sharedSecret, commitment: note.commitment, recipient: RECIPIENT, relayer: c.relayer, fee: c.fee },
    artifacts,
  )
  if (!(await snarkjs.groth16.verify(vkey, publicSignals.map(String), raw))) throw new Error(`${c.name}: proof failed off-chain verification`)
  out.push(`    // ${c.name}: recipient=${RECIPIENT} relayer=${c.relayer} fee=${c.fee}
    function ${c.name.toLowerCase()}() internal pure returns (Fixture memory f) {
        f.commitment = ${note.commitment};
        f.ephemeralPubKey = hex"${toHex(note.ephemeralPubKey).slice(2)}";
        f.viewTag = ${note.viewTag};
        f.recipient = ${checksumless(RECIPIENT)};
        f.relayer = ${checksumless(c.relayer)};
        f.fee = ${c.fee};
        f.proof.a = [uint256(${proof.a[0]}), ${proof.a[1]}];
        f.proof.b = [[uint256(${proof.b[0][0]}), ${proof.b[0][1]}], [uint256(${proof.b[1][0]}), ${proof.b[1][1]}]];
        f.proof.c = [uint256(${proof.c[0]}), ${proof.c[1]}];
    }`)
}

function checksumless(addr: Hex) {
  return `address(uint160(${BigInt(addr)}))`
}

const sol = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by backend/scripts/fixtures.ts — real proofs from frontend/public/circuits. Do not edit.
pragma solidity ^0.8.24;

import {StealthPool} from "../../src/StealthPool.sol";

library ProofFixtures {
    struct Fixture {
        uint256 commitment;
        bytes ephemeralPubKey;
        uint8 viewTag;
        address recipient;
        address relayer;
        uint256 fee;
        StealthPool.Proof proof;
    }

${out.join('\n\n')}
}
`
writeFileSync(join(repo, 'contracts', 'test', 'fixtures', 'ProofFixtures.sol'), sol)
console.log('Wrote contracts/test/fixtures/ProofFixtures.sol')
