// Pulls generated artifacts into the app:
//  - contract ABIs from Foundry's out/ (so the UI can never drift from the deployed interface)
//  - deployment addresses from contracts/deployments/<chainId>.json
//  - the snarkjs browser bundle for in-browser proving
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const app = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const contracts = resolve(app, '..', 'contracts')
const require = createRequire(import.meta.url)

// ABIs
const abiOut = join(app, 'lib', 'abi.ts')
const names = ['StealthPool', 'StealthKeyRegistry']
if (names.every((n) => existsSync(join(contracts, 'out', `${n}.sol`, `${n}.json`)))) {
  const body = names
    .map((n) => {
      const { abi } = JSON.parse(readFileSync(join(contracts, 'out', `${n}.sol`, `${n}.json`), 'utf8'))
      return `export const ${n[0].toLowerCase()}${n.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const\n`
    })
    .join('\n')
  writeFileSync(abiOut, `// AUTO-GENERATED by scripts/sync.mjs from contracts/out. Do not edit.\n\n${body}`)
  console.log('sync: ABIs updated')
} else if (!existsSync(abiOut)) {
  throw new Error('Run `forge build` in contracts/ first')
}

// Deployments
const depDir = join(contracts, 'deployments')
const deployments = {}
if (existsSync(depDir)) {
  for (const file of readdirSync(depDir).filter((f) => /^\d+\.json$/.test(f) && f !== '31337.json')) {
    const d = JSON.parse(readFileSync(join(depDir, file), 'utf8'))
    deployments[d.chainId] = d
  }
}
writeFileSync(join(app, 'lib', 'deployments.json'), `${JSON.stringify(deployments, null, 2)}\n`)
console.log(`sync: deployments for chains [${Object.keys(deployments).join(', ') || 'none'}]`)

// snarkjs browser bundle
mkdirSync(join(app, 'public'), { recursive: true })
copyFileSync(join(dirname(require.resolve('snarkjs')), 'snarkjs.min.js'), join(app, 'public', 'snarkjs.min.js'))
